### ISSUE TITLE
tson: Support custom types

### ISSUE THREAD

**Issue by gkubisa** [SyncOT/SyncOT#13]

**Comment by curran** [comment]
Is this issue about support for [OT types](https://github.com/ottypes)?

**Comment by gkubisa** [comment]
No, it's about allowing binary encoding and decoding of custom types using the [`tson` module](https://github.com/SyncOT/SyncOT/tree/master/packages/tson).

`tson` is similar to [BSON](http://bsonspec.org/), however, it's focused more on producing minimal encoding and less on traversability. Additionally, it'll support custom user-defined data types, which this issue is about. Custom types will allow further encoding efficiencies, for example `Message`, `Snapshot` and `Operation` types will be encoded without property names to produce smaller encoded values in less time.

It's not high priority for me ATM but it could be a good issue for new contributors to work on. :-)

**Comment by curran** [comment]
Thanks for clarifying :-)

**Comment by gkubisa** [comment]
I'm deprecating TSON in favour of JSON, as the custom format does not offer enough advantages to justify the complexity it adds.
