### ISSUE TITLE
Client Reconnection

### ISSUE THREAD

**Issue by gkubisa** [SyncOT/SyncOT#4]
Implement a client side module which tries to keep the client connected to the server at all times.

- Reconnect to the server using a configurable exponential back-off strategy.
- Support WebSocket with a fallback to SockJS.

**Comment by curran** [comment]
FWIW, I think it would be excellent to _not_ depend on `reconnecting-websocket`, as it's not being properly maintained (suffers from a connection delay bug with a [fix PR that's not being merged](https://github.com/pladaria/reconnecting-websocket/pull/94)).

**Comment by curran** [comment]
> Support WebSocket with a fallback to SockJS.

This feels odd, as SockJS already tries WebSocket as it's first option.

**Comment by gkubisa** [comment]
> FWIW, I think it would be excellent to not depend on reconnecting-websocket, as it's not being properly maintained (suffers from a connection delay bug with a fix PR that's not being merged).

I've no intention of using `reconnecting-websocket`.

>> Support WebSocket with a fallback to SockJS.

> This feels odd, as SockJS already tries WebSocket as it's first option.

I'd love to use SockJS only, however, it supports only string payloads, so it's not as efficient as it could be for transferring binary data, while all SyncOT payloads are binary.

**Comment by curran** [comment]
Ah I see. That makes sense.

**Comment by gkubisa** [comment]
I decided that this is outside the scope of SyncOT after all. I'll write a guide later about managing connections for SyncOT.

**Comment by gkubisa** [comment]
I actually implemented it in SyncOT as [StreamManager](https://github.com/SyncOT/SyncOT/blob/271632ac149bbf049fcdef63d62d666a63cf69fa/packages/connection/src/manager.ts#L54) which work with [Connection](https://github.com/SyncOT/SyncOT/blob/271632ac149bbf049fcdef63d62d666a63cf69fa/packages/connection/src/connection.ts#L825).
